version: "2.1"
services:
  duckdns:
    image: ghcr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - SUBDOMAINS=subdominio1,subdominio2
      - TOKEN=tuDNSACA
    restart: always
